### ISSUE TITLE
Suggestion for the README

### ISSUE THREAD

**Issue by williamdes** [phar-io/manifest#14]
Reading the readme would make me want to use the project, one thing is missing: you put a line that does a var_dump, but why not also adding the output of the var_dump?

**Comment by williamdes** [comment]
Hi @theseer 
The XML part does not render :/

**Comment by theseer** [comment]
Sometimes I hate markdown. Why ever there has to be a blank line...

**Comment by williamdes** [comment]
> Sometimes I hate markdown. Why ever there has to be a blank line...

Yeah..
Thanks a lot
