### ISSUE TITLE
Dead links found in README.md

### ISSUE THREAD

**Issue by llaville** [phar-io/manifest#17]
As a contributor to [Mega-Linter](https://github.com/megalinter/megalinter) project, I used it as a QA tools that checks lot of things, including dead links in Markdown files.

[markdown-lint-check](https://github.com/tcort/markdown-link-check) do the job and report that 2 dead links were found in README.md, about SensioLabsInsight button

```
      ERROR: 2 dead links found!
      [✖] https://insight.sensiolabs.com/projects/d8cc6035-69ad-477d-bd1a-ccc605480fd7 → Status: 0
      [✖] https://insight.sensiolabs.com/projects/d8cc6035-69ad-477d-bd1a-ccc605480fd7/mini.png → Status: 0
```

See https://github.com/phar-io/manifest/blame/master/README.md#L7

**Comment by theseer** [comment]
Nice catch.

**Comment by theseer** [comment]
All the badges are old and should be replaced with github action based states.

I thus removed them all for now.
