### ISSUE TITLE
Make `manifest.xsd` available publicly

### ISSUE THREAD

**Issue by localheinz** [phar-io/manifest#25]
It would be great if [`manifest.xsd`](https://github.com/phar-io/manifest/blob/master/manifest.xsd) were publicly available to reference it in a `manifest.xml`.

Currently, the only option would be to use https://raw.githubusercontent.com/phar-io/manifest/master/manifest.xsd as a URL.

**Comment by theseer** [comment]
Done.

The namespace URL `https://phar.io/xml/manifest/1.0` now redirects to github's usercontent url.

**Comment by localheinz** [comment]
Thank you, @theseer!
